email:
  imap: "imap.server:port"
  login: "myemail@server.com"
  password: "mypassword"
  mailbox: "INBOX"
targetFrom: "info@account.netflix.com"
targetSubject: "Important : comment mettre à jour votre foyer Netflix"